title: CCCS Public Register and Consultation
remote_theme: opendocsg/opendoc-theme
repository: opendocsg/opendoc-template
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
section_order:
  - CCS Fines Capacitor Manufacturers Involved in Global Cartel for Price-fixing and Information Exchange
styling_options:
  primary_brand_color: '#444'
  logo_path: /assets/logo.png
  opendoc_logo_path: /assets/images/logo-full.png
